# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
pygments: true
encoding: utf-8
markdown: kramdown

title: Egor Hamaliy
description: Stylish Jekyll Theme
author:
  name: Egor Hamaliy
  email: egor.hamaliy@gmail.com
  github: egorhm
  twitter: egor_hm
  bio: Ruby/Erlang/Java developer at EPAM Systems
  email_md5: dd050e6d8b0f09cf2c0dda78382e6944

# rss_path: feed.xml
# categories_path: categories.html
tags_path: tags.html

BASE_PATH: http://egorhm.github.io

# All links will be namespaced by BASE_PATH if defined.
# Links in your website should always be prefixed with {{ site.BASE_PATH }}
# Do not put a "/" at the end of the url.
#
# CNAME (http://yourcustomdomain.com)
#   DO NOT SET BASE_PATH JUST LEAVE IT BLANK
#   (urls will be prefixed with "/" and work relatively)
#
# GitHub Pages (http://username.github.io)
#   DO NOT SET BASE_PATH JUST LEAVE IT BLANK
#   (urls will be prefixed with "/" and work relatively)
#
# GitHub Project Pages (http://username.github.io/project-name)
#  A GitHub Project site exists in the `gh-pages` branch of one of your repositories.
#  REQUIRED! Set BASE_PATH to "http://username.github.io/project-name"
